<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-CVK207NV" failures="1" tests="2" name="Test(failed)" time="0.097" errors="0" timestamp="2022-06-15T19:46:43 IST">
  <testcase classname="xmlStudy.FailedIncludeMyTest" name="MyMethod1" time="0.017">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at xmlStudy.FailedIncludeMyTest.MyMethod1(FailedIncludeMyTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- MyMethod1 -->
  <testcase classname="xmlStudy.FailedIncludeMyTest" name="MyMethod3" time="0.006"/>
  <testcase classname="xmlStudy.FailedIncludeMyTest" name="MyMethod6" time="0.0">
    <ignored/>
  </testcase> <!-- MyMethod6 -->
  <testcase classname="xmlStudy.FailedIncludeMyTest" name="MyMethod5" time="0.0">
    <ignored/>
  </testcase> <!-- MyMethod5 -->
  <testcase classname="xmlStudy.FailedIncludeMyTest" name="MyMethod2" time="0.0">
    <ignored/>
  </testcase> <!-- MyMethod2 -->
  <testcase classname="xmlStudy.FailedIncludeMyTest" name="MyMethod7" time="0.0">
    <ignored/>
  </testcase> <!-- MyMethod7 -->
  <testcase classname="xmlStudy.FailedIncludeMyTest" name="MyMethod4" time="0.0">
    <ignored/>
  </testcase> <!-- MyMethod4 -->
</testsuite> <!-- Test(failed) -->
